### ISSUE TITLE
tracker.pyw doesn't open on Windows 10

### ISSUE THREAD

**Issue by ph3nic** [MizaGBF/GBFLT#2]
**System Informations:**
- GBFLT Version: v1.46
 - OS: Windows 10
- Python Version: (if known) 3.12.0-amd64

**Describe the bug**
can't start the tracker , opens python but disappear instantly

**To Reproduce**
1. Go to: tracker.pyw
2. Click on : tracker.pyw
. See error

**Expected behavior**
GBFLT booting 

Screenshots and contexts : 

wanted to try loot tracker since my crew is using it
i installed python 3.10 ; 3.11 and 3.12 but it still gives me this error.
tried many times to reinstall GBFLT
![image](https://github.com/MizaGBF/GBFLT/assets/152729447/7f59048b-2df7-4a2c-846b-e73bd1590f3f)

**Comment by MizaGBF** [comment]
Just a guess: did you unzip before running it?

**Comment by ph3nic** [comment]
yes i did

**Comment by ph3nic** [comment]
before and after as i've tried multiples times

**Comment by MizaGBF** [comment]
Go to the assets folder, run troubleshooting.pyw
does it say anything?

**Comment by ph3nic** [comment]
its the screenshot i attached 
can show it again
![image](https://github.com/MizaGBF/GBFLT/assets/152729447/966c37b8-6a0e-4829-a43e-872fbc73c961)

**Comment by MizaGBF** [comment]
Ah my bad.
As for the tracker itself, nothing happens at all?

**Comment by ph3nic** [comment]
yes , it pops python and it closes itself

**Comment by ph3nic** [comment]
https://www.youtube.com/watch?v=MI-Thk9yJco 
should have send this

**Comment by ph3nic** [comment]
me recording opening tracker

**Comment by MizaGBF** [comment]
From the look of it, you're still inside the zip file (I can tell from the compression ratio shown on the right).
Go back a folder, right click on GBFLT-main.zip, extract.
Then go in the folder created from it and it should run.

**Comment by ph3nic** [comment]
https://www.youtube.com/watch?v=38JO9Ybf9bg

**Comment by MizaGBF** [comment]
[test.zip](https://github.com/MizaGBF/GBFLT/files/13540299/test.zip)
Try to run the python file inside.

If it works, a message box will popup with your python version.
If it doesn't work, it will appear in the console.
Tell me what it does and the python version displayed.

**Comment by ph3nic** [comment]
![image](https://github.com/MizaGBF/GBFLT/assets/152729447/4d99d749-ec7b-46b8-a91d-12d7cb21e538)

**Comment by ph3nic** [comment]
pop-up message with written : your python version is 3.12

**Comment by MizaGBF** [comment]
I'm a bit at a loss.
Try to run troubleshooting.pyw again (Be certain to not be in the zip file. You should probably delete it btw)

**Comment by ph3nic** [comment]
![image](https://github.com/MizaGBF/GBFLT/assets/152729447/c4a782bc-1598-477e-a019-87386ab19136)

same thing

**Comment by MizaGBF** [comment]
Does the test.py I gave you had a file icon or did it open a prompt to ask you what to run the file with?

Maybe that's the problem.
You can try the following: Instead of clicking on Python when it asks you, do "more applications" then "search an application on this computer" at the bottom (or something like this).

Then go to where you installed Python (Probably in C:\something).

In the python folder, you should see python.exe and pythonw.exe. This is a pyw file so pick pythonw.
If it works, make it the default application so you don't have to search it again;

**Comment by ph3nic** [comment]
https://www.youtube.com/watch?v=yl_UPq7nJNg

the test.py opened without a prompt
![image](https://github.com/MizaGBF/GBFLT/assets/152729447/7af26393-2883-4ee4-a133-ef771f661161)

**Comment by ph3nic** [comment]
asked a friend of mine to DL it and 
it seems it's a me problem

**Comment by MizaGBF** [comment]
That's probably it then. I think you're trying to run the file with the python launcher which is something else entirely.
Try what I said above.

**Comment by ph3nic** [comment]
https://www.youtube.com/watch?v=7wee0rh8o6o
cant say it's working sadly
it is pythonw that im running right

**Comment by MizaGBF** [comment]
Click the one without the rocket on the icon (rocket = launcher).

**Comment by ph3nic** [comment]
https://youtu.be/kb-PSvwPUGA

**Comment by ph3nic** [comment]
oh it's working now
![image](https://github.com/MizaGBF/GBFLT/assets/152729447/dca3ee2f-3ca1-42ab-84c3-3c3b9d61820d)

**Comment by MizaGBF** [comment]
You picked python instead of pythonw on the last video (It should have opened still, not sure why it didn't).
Make sure to make it the default application for this file so you don't have to go to the python folder every time (there should be a checkbox along the way to make it the default).

**Comment by ph3nic** [comment]
thanks mate , have a good evening

**Comment by MizaGBF** [comment]
(By the way, you really should activate file extensions in the explorer to be sure on what you're clicking, not sure why Microsoft isn't making it the default setting. Just click "Affichage" on the top and there should be a check box to not hide file extensions)

**Comment by MizaGBF** [comment]
You're welcome.
